language: node_js

node_js:
  - '10'

git:
  depth: 1

before_install:
  - npm i -g npm

install:
  - npm install

script:
  - npm run lint
  - npm run build:ci

cache: npm

deploy:
  - provider: s3
    access_key_id: $QN_AK
    secret_access_key: $QN_SK
    bucket: '82vi6u'
    skip_cleanup: true
    region: cn-south-1
    local_dir: dist
    endpoint: https://s3-cn-south-1.qiniucs.com
    on:
      branch: develop
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    fqdn: app.gh.tossp.com
    local_dir: dist
    on:
      branch: develop
