language: node_js

node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

git:
  depth: 1

before_install:
  - npm i -g npm

install:
  - npm install

script:
  - npm run lint
  - npm run build

cache: npm
