language: node_js

node_js:
  - '10'

git:
  depth: 1

before_install:
  - npm i -g npm

install:
  - npm install

script:
  - npm run lint
  - npm run build:ci

cache: npm

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: app-dashboard.gh.tossp.com
  local_dir: dist
  on:
    branch: develop
